### PR TITLE
Feature Signup page

### PR DESCRIPTION
**Pull request by Avin008**
### Signup page Includes:

image

### CODE REVIEW

**Review by Nagashree01 — APPROVED** [review]
Good to go

**Comment by anand-tiwari** [comment]
i think you should change netlify setting to deploy all your branch & paste exact page url of related to PR. so we can preview UI changes

**Review by anand-tiwari — APPROVED** [review]
LGTM

**Comment by ganesh-kanchi** [comment]
> i think you should change netlify setting to deploy all your branch & paste exact page url of related to PR. so we can preview UI changes

netlify has commented the deploy preview already

**Comment by ganesh-kanchi** [comment]
> > i think you should change netlify setting to deploy all your branch & paste exact page url of related to PR. so we can preview UI changes
> 
> netlify has commented the deploy preview already

sorry he doesn't have an index.html in his repository

**Pull request merged**
